Repository gravitee-io/gravitee-kubernetes-operator, pull requests merged in 2024-07, with the labels that each got.

#712 fix: persist false values for application disabled membership notif
  api/model/application/application.go
  docs/api/reference.md
  helm/gko/crds/gravitee.io_applications.yaml
Labels: apply-on-master, apply-on-4-4-x

#713 docs: fix fetcher examples
  examples/apim/api_definition/v2/api-with-page-swagger-http-fetcher.yml
  examples/apim/api_definition/v4/api-v4-with-page-swagger-http-fetcher.yml
Labels: apply-on-4-4-x

#724 feat: allow users to choose the API execution_mode
  api/model/api/v2/api.go
  docs/api/reference.md
  helm/gko/crds/gravitee.io_apidefinitions.yaml
Labels: apply-on-4-4-x

#678 chore(deps): update kubernetes packages to v0.30.2
  go.mod
  go.sum
Labels: apply-on-4-4-x

#736 ci: set image pull policy to always
  .circleci/config.yml
Labels: apply-on-4-4-x, apply-on-4-3-x
